cfg_version: 1.0.0
command-aliases: sell
messages-output: ACTION_BAR
price:
  levels:
    default: 100
    for-each: 50
  module-types:
    ACTIVE_ITEMS: 50.0
    ARROWS: 50.0
    BUFFS: 50.0
    COMBAT_LOG: 50.0
    CONSUMABLES: 50.0
    CUSTOM_ITEMS: 50.0
    DROPS: 50.0
    ESSENCES: 50.0
    EXTRACTOR: 50.0
    GEMS: 50.0
    IDENTIFY: 50.0
    ITEM_HINTS: 50.0
    MAGIC_DUST: 50.0
    NOTIFICATIONS: 50.0
    PARTY: 50.0
    REPAIR: 50.0
    RESOLVE: 50.0
    RUNES: 50.0
    SELL: 50.0
    SETS: 50.0
    SOULBOUND: 50.0
    TIERS: 50.0
  item-types:
    DIAMOND_SWORD: 500
    EMERALD: 300
  item-stats:
    CRITICAL_RATE: 90
    DIRECT_DAMAGE: 50.0
    AOE_DAMAGE: 50.0
    PVP_DAMAGE: 50.0
    PVE_DAMAGE: 50.0
    DODGE_RATE: 50.0
    ACCURACY_RATE: 50.0
    BLOCK_RATE: 50.0
    BLOCK_DAMAGE: 50.0
    LOOT_RATE: 50.0
    BURN_RATE: 50.0
    PVP_DEFENSE: 50.0
    PVE_DEFENSE: 50.0
    CRITICAL_DAMAGE: 50.0
    DURABILITY: 50.0
    DURABILITY_UNBREAK: 50.0
    MOVEMENT_SPEED: 50.0
    PENETRATION: 50.0
    ATTACK_SPEED: 50.0
    VAMPIRISM: 50.0
    MAX_HEALTH: 50.0
    BLEED_RATE: 50.0
    DISARM_RATE: 50.0
    RANGE: 50.0
    SALE_PRICE: 50.0
  armor-types:
    physical: 35
    magical: 25.0
    poison: 25.0
    fire: 25.0
    water: 25.0
    wind: 25.0
  damage-types:
    physical: 45
    magical: 25.0
    poison: 25.0
    fire: 25.0
    water: 25.0
    wind: 25.0
gui:
  title: '&4&l<&4&nSelling&4&l>'
  size: 54
  item-slots: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44
  content:
    filler_black:
      material: STAINED_GLASS_PANE:15:1
      skull-hash: ''
      enchanted: false
      name: ''
      lore: []
      slots: 45,46,47,48,49,50,51,52,53
      type: NONE
    sell:
      material: STAINED_GLASS_PANE:5:1
      skull-hash: ''
      enchanted: false
      name: '&aSell!'
      lore:
      - '&7> &fTotal cost:             &a%cost%'
      - '&8&m                                      '
      - '&7Sell all items in GUI.'
      slots: '49'
      type: ACCEPT
